spring:
  application:
    name: security-jmv

  datasource:
    url: jdbc:postgresql://localhost:5432/security-jmv
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

jwt:
  # Chave de desenvolvimento (NAO usar em producao). Sobrescreva definindo a variavel de ambiente SECRET_KEY.
  secret-key: ${SECRET_KEY:9UxwUiFcP4yyOpw9Q2uL5Hev5v99DWNxsmyDmG7v0Si9BBRpwfSFoUVEYpQQC5r4jYUSulbTiNHkRgU3B+dOCg==}
  expiration-time: ${EXPIRATION:1800000} # 30 minutos em milissegundos
  refresh-expiration-time: ${REFRESH-TOKEN-EXPIRATION:604800000}  # 7 dias em milissegundos
